### ISSUE TITLE
Make Transformation object from intervals, cx[][] and cy[][]

### ISSUE THREAD

**Issue by StephanPreibisch** [fiji/bUnwarpJ#2]
Hi @iarganda,

not sure if this is really an issue, but here it is more visible if other people experience the same problem. I apply the non-rigid transformation myself using Transformation.transform( u, v, l, true );

This works great, however, if I want to save and load the transformation, I end up with:
int intervals;
double[][] cx, double[][] cy;

How do I create a Transformation object out of that in order to use the above method in order to apply it?

Thanks so much,
Stephan

**Comment by iarganda** [comment]
So you would like to have a couple of methods to save/load transformations from file without using the GUI, right? We run into that problem before for the Register Virtual Stack Slices plugin and as a solution we created a new class (https://github.com/trakem2/TrakEM2/blob/master/TrakEM2_/src/main/java/bunwarpj/trakem2/transform/CubicBSplineTransform.java). But I guess it makes more sense to create the methods in the Transformation class itself. 

I'm working on the bug you reported so I'll do it now. Give me a few minutes.

**Comment by iarganda** [comment]
Done!
